[package]
name = "penning-helper-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0", features = ["wayland", "wgpu"] }
penning-helper-turflists = { path = "../penning-helper-turflists" }
penning-helper-types = { path = "../penning-helper-types" }
rfd = "0.11.4"
penning-helper-conscribo = { path = "../penning-helper-conscribo" }
egui_extras = { version = "0.22.0", features = ["datepicker"] }
egui_dock = "0.6.3"
penning-helper-config = { path = "../penning-helper-config" }
egui = { version = "0.22.0" }
dirs = "5.0.1"
regex = "1.9.5"
penning-helper-pdf = { path = "../penning-helper-pdf" }
open = "5.0.0"
penning-helper-sepa = { path = "../penning-helper-sepa" }
penning-helper-mail = { path = "../penning-helper-mail" }
chrono = "0.4.31"
