[package]
name = "penning-helper-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0", features = ["wayland", "wgpu"] }
penning-helper-turflists = { path = "../penning-helper-turflists" }
penning-helper-types = { path = "../penning-helper-types" }
rfd = "0.11.4"
penning-helper-conscribo = { path = "../penning-helper-conscribo" }
egui_extras = "0.22.0"
